# Generated by Django 3.2.7 on 2021-09-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '__first__'),
        ('Cartões', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcards',
            new_name='Flashcard',
        ),
    ]
